"""Monitoring module for SupoClip backend"""

from .metrics import (
    PrometheusMiddleware,
    get_metrics,
    get_metrics_content_type,
    track_video_processing_stage,
    track_worker_task,
    track_db_query,
    update_resource_metrics,
    # Export individual metrics for direct access
    http_requests_total,
    http_request_duration_seconds,
    http_requests_in_progress,
    video_processing_duration_seconds,
    video_processing_total,
    video_processing_in_progress,
    clips_generated_total,
    worker_queue_depth,
    worker_queue_processing_time_seconds,
    worker_queue_tasks_processed_total,
    active_workers,
    failed_workers_total,
    errors_total,
    exceptions_total,
    cpu_usage_percent,
    memory_usage_bytes,
    memory_usage_percent,
    disk_usage_bytes,
    disk_usage_percent,
    disk_free_bytes,
    db_query_duration_seconds,
    db_connections_active,
    db_connections_idle,
    app_info,
    app_uptime_seconds,
)

from .integration import setup_monitoring
from .health import get_health_status

__all__ = [
    'setup_monitoring',
    'get_health_status',
    'PrometheusMiddleware',
    'get_metrics',
    'get_metrics_content_type',
    'track_video_processing_stage',
    'track_worker_task',
    'track_db_query',
    'update_resource_metrics',
    'http_requests_total',
    'http_request_duration_seconds',
    'http_requests_in_progress',
    'video_processing_duration_seconds',
    'video_processing_total',
    'video_processing_in_progress',
    'clips_generated_total',
    'worker_queue_depth',
    'worker_queue_processing_time_seconds',
    'worker_queue_tasks_processed_total',
    'active_workers',
    'failed_workers_total',
    'errors_total',
    'exceptions_total',
    'cpu_usage_percent',
    'memory_usage_bytes',
    'memory_usage_percent',
    'disk_usage_bytes',
    'disk_usage_percent',
    'disk_free_bytes',
    'db_query_duration_seconds',
    'db_connections_active',
    'db_connections_idle',
    'app_info',
    'app_uptime_seconds',
]
